############################################
#              Coins made by               #
#              damt & refine               #
############################################

SETTINGS:
  ENABLE-PAY: true
  PLACEHOLDERAPI: true

STORAGE:
  MONGO-STORAGE: false
  MONGO:
    URI-MODE: true
    NORMAL:
      HOST: 127.0.0.1
      PORT: '27017'
      DATABASE: RefineCoins
      AUTHENTICATION:
        ENABLED: false
        USERNAME: ''
        PASSWORD: ''
    URI:
      DATABASE: RefineCoins
      CONNECTION_STRING: mongodb://127.0.0.1:27017/RefineCoins